# release-plz configuration for workspace with independent package releases
[workspace]
# Enable conventional commits parsing
git_release_enable = true
git_tag_enable = true
changelog_update = true
publish = false

# Package-specific configurations
[[package]]
name = "user-lib"
# Changelog path relative to package root
changelog_path = "CHANGELOG.md"
# Custom git tag pattern for this package
git_tag_name = "user-lib-v{{ version }}"
# Custom git release name pattern
git_release_name = "user-lib-v{{ version }}"

[[package]]
name = "user-cli"
# Changelog path relative to package root
changelog_path = "CHANGELOG.md"
# Custom git tag pattern for this package
git_tag_name = "user-cli-v{{ version }}"
# Custom git release name pattern
git_release_name = "user-cli-v{{ version }}"

# Changelog configuration
[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
"""
# Commit types to include in changelog
[[changelog.commit_parsers]]
message = "^feat"
group = "Added"

[[changelog.commit_parsers]]
message = "^fix"
group = "Fixed"

[[changelog.commit_parsers]]
message = "^docs"
group = "Documentation"

[[changelog.commit_parsers]]
message = "^style"
group = "Styling"

[[changelog.commit_parsers]]
message = "^refactor"
group = "Refactoring"

[[changelog.commit_parsers]]
message = "^perf"
group = "Performance"

[[changelog.commit_parsers]]
message = "^test"
group = "Testing"

[[changelog.commit_parsers]]
message = "^build"
group = "Build System"

[[changelog.commit_parsers]]
message = "^ci"
group = "CI/CD"

[[changelog.commit_parsers]]
message = "^chore"
group = "Miscellaneous"

[[changelog.commit_parsers]]
message = "^.*"
group = "Other"
