
[package]
name = "user-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "user-cli"
path = "src/main.rs"

[dependencies]
user-lib = { path = "../user-lib" }
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
