
[package]
name = "user-cli"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "user-cli"
path = "src/main.rs"

[dependencies]
user-lib = { path = "../user-lib" }
clap = { workspace = true }
anyhow = { workspace = true }
